### ISSUE TITLE
Error: timerBrand: symbol "[Symbol(replaced:35)]"

### ISSUE THREAD

**Issue by Jorge-Lopes** [Jorge-Lopes/agoric-sdk-liquidation-visibility#21]
## Describe the bug
When executing the function `runAuction` in the bootstrap test-liquidation-visibility.js, the `liveAuctionSchedule` object will have as `timerBrand` the value `Symbol(replaced:35)`.

Commit 50b210330cfb58652f481604594cff23e493499c

The object is returned by the `getSchedules` method:
```js
const { liveAuctionSchedule } = await EV(
    auctioneerKit.publicFacet,
  ).getSchedules();
```

### liveAuctionSchedule object
```
LOG: liveAuctionSchedule  {
  clockStep: { relValue: 180n, timerBrand: Symbol(replaced:35) },
  endRate: 6500n,
  endTime: { absValue: 5042n, timerBrand: Symbol(replaced:35) },
  lockTime: { absValue: 1802n, timerBrand: Symbol(replaced:35) },
  startDelay: { relValue: 2n, timerBrand: Symbol(replaced:35) },
  startTime: { absValue: 3602n, timerBrand: Symbol(replaced:35) },
  steps: 8n
}
```

## Error message

```
  Error {
    message: 'timestamp: timerBrand: symbol "[Symbol(replaced:35)]" - Must be a remotable (TimerBrand)',
  }
```

**Comment by anilhelvaci** [comment]
Did you try checking only the `absValue` using `t.like`?

**Comment by Jorge-Lopes** [comment]
The problem was not being generated when asserting any value of `liveAuctionSchedule` but instead when the `nominalStart` was being calculated.

But the solution proposed is effective as well, as expected.

**Comment by anilhelvaci** [comment]
Did you find out why `[Symbol(replaced:35)]` being generated instead of a normal `TimerBrand`? I thought it might be related to some marshalling thing but the value is coming directly from the auctioneer, so I'm curious why that might be? Did you check other tests in `bootstrapTests` directory? Is this behavior present in there also? @Jorge-Lopes
